---
abstract: 'L<Perl::Version> type for Moose classes'
author:
  - 'Roman F. <romanf@cpan.org>'
build_requires:
  Moose: 0
  Moose::Util::TypeConstraints: 0
  Test::More: 0
  ok: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Types-PerlVersion
requires:
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  Perl::Version: 0
  namespace::clean: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/moltar/MooseX-Types-PerlVersion.git
version: v0.1.0
